mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=January2799
    - MYSQL_DATABASE=root
    - MYSQL_ROOT_PASSWORD=January2799
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"